name: Question
description: Ask your question
labels: ['question']
body:
  - type: markdown
    attributes:
      value: Please note, the OSCAL [Q&A discussion board](https://github.com/usnistgov/OSCAL/discussions/categories/q-a) is a more appropriate place for asking most questions.
  - type: textarea
    id: question-text
    attributes:
      label: Question
      description: Please enter your question
    validations:
      required: true
